import type { F1Challenge } from './types';

// Static F1 challenges using Wikipedia Commons & other public domain images
// These are used when Reddit is not accessible
export const FALLBACK_CHALLENGES: F1Challenge[] = [
  {
    id: 'fb-001', type: 'zoomed',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/2019_Formula_One_tests_Barcelona%2C_Verstappen_%2847326925492%29.jpg/1280px-2019_Formula_One_tests_Barcelona%2C_Verstappen_%2847326925492%29.jpg',
    title: 'Dutch driver in Red Bull colors',
    answer: 'Max Verstappen', questionType: 'driver',
    options: ['Max Verstappen', 'Lewis Hamilton', 'Daniel Ricciardo', 'Sergio Perez'],
    hint: 'World Champion #1 | Dutch | Red Bull',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 2,
  },
  {
    id: 'fb-002', type: 'pixelated',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Lewis_Hamilton_2016_Malaysia_2.jpg/1280px-Lewis_Hamilton_2016_Malaysia_2.jpg',
    title: 'British driver in silver',
    answer: 'Lewis Hamilton', questionType: 'driver',
    options: ['Lewis Hamilton', 'Nico Rosberg', 'George Russell', 'Valtteri Bottas'],
    hint: '7x World Champion | British | Mercedes',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 2,
  },
  {
    id: 'fb-003', type: 'zoomed',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Sebastian_Vettel_2019_Ferrari.jpg/1280px-Sebastian_Vettel_2019_Ferrari.jpg',
    title: 'German driver in red',
    answer: 'Sebastian Vettel', questionType: 'driver',
    options: ['Sebastian Vettel', 'Charles Leclerc', 'Carlos Sainz', 'Kimi Raikkonen'],
    hint: '4x World Champion | German | Ferrari era',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 3,
  },
  {
    id: 'fb-004', type: 'pixelated',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Charles_Leclerc_2019_Ferrari_%28cropped%29.jpg/800px-Charles_Leclerc_2019_Ferrari_%28cropped%29.jpg',
    title: 'Monegasque driver at Scuderia',
    answer: 'Charles Leclerc', questionType: 'driver',
    options: ['Charles Leclerc', 'Carlos Sainz', 'Sebastian Vettel', 'Fernando Alonso'],
    hint: 'Monégasque | Ferrari | Won on home soil... almost',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 3,
  },
  {
    id: 'fb-005', type: 'zoomed',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Fernando_Alonso_2021_Bahrain_FP2.jpg/1280px-Fernando_Alonso_2021_Bahrain_FP2.jpg',
    title: 'Veteran Spanish driver',
    answer: 'Fernando Alonso', questionType: 'driver',
    options: ['Fernando Alonso', 'Carlos Sainz', 'Pedro De La Rosa', 'Marc Gene'],
    hint: '2x World Champion | Spanish | "I am ready"',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 3,
  },
  {
    id: 'fb-006', type: 'pixelated',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Lando_Norris_2023_Bahrain_GP_%28cropped%29.jpg/800px-Lando_Norris_2023_Bahrain_GP_%28cropped%29.jpg',
    title: 'Young British McLaren driver',
    answer: 'Lando Norris', questionType: 'driver',
    options: ['Lando Norris', 'Oscar Piastri', 'George Russell', 'Alexander Albon'],
    hint: 'British | McLaren | Papaya driver',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 4,
  },
  {
    id: 'fb-007', type: 'zoomed',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Kimi_R%C3%A4ikk%C3%B6nen_2018_Malaysia.jpg/1280px-Kimi_R%C3%A4ikk%C3%B6nen_2018_Malaysia.jpg',
    title: '"Bwoah" — iceman of F1',
    answer: 'Kimi Raikkonen', questionType: 'driver',
    options: ['Kimi Raikkonen', 'Valtteri Bottas', 'Mika Hakkinen', 'Felipe Massa'],
    hint: 'Finnish | Known for minimal words | Iceman',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 4,
  },
  {
    id: 'fb-008', type: 'pixelated',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Ayrton_Senna_1991_San_Marino_Grand_Prix_%28cropped%29.jpg/800px-Ayrton_Senna_1991_San_Marino_Grand_Prix_%28cropped%29.jpg',
    title: 'Brazilian F1 legend',
    answer: 'Ayrton Senna', questionType: 'driver',
    options: ['Ayrton Senna', 'Alain Prost', 'Nelson Piquet', 'Rubens Barrichello'],
    hint: '3x Champion | Brazilian | Racing immortal',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 6,
  },
  {
    id: 'fb-009', type: 'zoomed',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Michael_Schumacher_2012_Bahrain_race.jpg/1280px-Michael_Schumacher_2012_Bahrain_race.jpg',
    title: 'German Ferrari legend',
    answer: 'Michael Schumacher', questionType: 'driver',
    options: ['Michael Schumacher', 'Sebastian Vettel', 'Nico Rosberg', 'Ralf Schumacher'],
    hint: '7x Champion | German | The greatest?',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 5,
  },
  {
    id: 'fb-010', type: 'pixelated',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Nico_Rosberg_2015_Malaysia.jpg/1280px-Nico_Rosberg_2015_Malaysia.jpg',
    title: 'German driver who quit at the top',
    answer: 'Nico Rosberg', questionType: 'driver',
    options: ['Nico Rosberg', 'Lewis Hamilton', 'Michael Schumacher', 'Sebastian Vettel'],
    hint: '2016 Champion | Retired immediately after | German',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 5,
  },
  {
    id: 'fb-011', type: 'zoomed',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/George_Russell_%28driver%2C_cropped%29.jpg/800px-George_Russell_%28driver%2C_cropped%29.jpg',
    title: 'British Mercedes driver',
    answer: 'George Russell', questionType: 'driver',
    options: ['George Russell', 'Lewis Hamilton', 'Alexander Albon', 'Lando Norris'],
    hint: 'British | Mercedes | Williams graduate',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 4,
  },
  {
    id: 'fb-012', type: 'pixelated',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Jenson_Button_2009_Bahrain_2.jpg/1280px-Jenson_Button_2009_Bahrain_2.jpg',
    title: '2009 World Champion',
    answer: 'Jenson Button', questionType: 'driver',
    options: ['Jenson Button', 'Lewis Hamilton', 'Rubens Barrichello', 'Kimi Raikkonen'],
    hint: 'British | Brawn GP | "It\'s hammer time"',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 6,
  },
  // Teams
  {
    id: 'fb-013', type: 'zoomed',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Ferrari_logo.svg/800px-Ferrari_logo.svg.png',
    title: 'The prancing horse',
    answer: 'Ferrari', questionType: 'team',
    options: ['Ferrari', 'Alfa Romeo', 'Maserati', 'Lamborghini'],
    hint: 'Italian | Most iconic F1 team | Red cars',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 1,
  },
  {
    id: 'fb-014', type: 'pixelated',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/McLaren_logo_2.svg/800px-McLaren_logo_2.svg.png',
    title: 'Papaya colored British constructor',
    answer: 'McLaren', questionType: 'team',
    options: ['McLaren', 'Williams', 'Alpine', 'Haas'],
    hint: 'British | Papaya orange | Woking based',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 2,
  },
  // Circuits
  {
    id: 'fb-015', type: 'zoomed',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Monaco_Formula_1_track_map.svg/800px-Monaco_Formula_1_track_map.svg.png',
    title: 'Street circuit through a principality',
    answer: 'Monaco', questionType: 'circuit',
    options: ['Monaco', 'Singapore', 'Baku', 'Melbourne'],
    hint: 'Street circuit | Principality | No overtaking',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 2,
  },
  {
    id: 'fb-016', type: 'pixelated',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Monza_track_map.svg/800px-Monza_track_map.svg.png',
    title: 'Temple of Speed in Italy',
    answer: 'Monza', questionType: 'circuit',
    options: ['Monza', 'Imola', 'Barcelona', 'Hockenheim'],
    hint: 'Temple of Speed | Italian GP | Tifosi',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 3,
  },
  {
    id: 'fb-017', type: 'zoomed',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Silverstone_Circuit_2020.svg/800px-Silverstone_Circuit_2020.svg.png',
    title: 'Home of the British Grand Prix',
    answer: 'Silverstone', questionType: 'circuit',
    options: ['Silverstone', 'Donington Park', 'Brands Hatch', 'Spa-Francorchamps'],
    hint: 'British GP | Former airfield | Maggots & Becketts',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 3,
  },
  {
    id: 'fb-018', type: 'pixelated',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Spa-Francorchamps_circuit_map.svg/800px-Spa-Francorchamps_circuit_map.svg.png',
    title: 'Belgian circuit with Eau Rouge',
    answer: 'Spa-Francorchamps', questionType: 'circuit',
    options: ['Spa-Francorchamps', 'Zandvoort', 'Hockenheim', 'Monza'],
    hint: 'Belgian GP | Eau Rouge | Weather lottery',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 4,
  },
  {
    id: 'fb-019', type: 'zoomed',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Suzuka_circuit_map.svg/800px-Suzuka_circuit_map.svg.png',
    title: 'Figure-of-eight Japanese circuit',
    answer: 'Suzuka', questionType: 'circuit',
    options: ['Suzuka', 'Fuji Speedway', 'Shanghai', 'Singapore'],
    hint: 'Japanese GP | Figure-8 | Honda home',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 4,
  },
  {
    id: 'fb-020', type: 'pixelated',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Bahrain_International_Circuit.svg/800px-Bahrain_International_Circuit.svg.png',
    title: 'Night race desert circuit',
    answer: 'Bahrain', questionType: 'circuit',
    options: ['Bahrain', 'Abu Dhabi', 'Jeddah', 'Qatar'],
    hint: 'Desert GP | Floodlit | Season opener',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 3,
  },
  // More drivers
  {
    id: 'fb-021', type: 'zoomed',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Valtteri_Bottas_2017_Malaysia.jpg/800px-Valtteri_Bottas_2017_Malaysia.jpg',
    title: 'Finnish Mercedes driver',
    answer: 'Valtteri Bottas', questionType: 'driver',
    options: ['Valtteri Bottas', 'Kimi Raikkonen', 'Mika Hakkinen', 'Heikki Kovalainen'],
    hint: 'Finnish | Wore #77 | "To whom it may concern"',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 5,
  },
  {
    id: 'fb-022', type: 'pixelated',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Daniel_Ricciardo_2018_Malaysia_%28cropped%29.jpg/800px-Daniel_Ricciardo_2018_Malaysia_%28cropped%29.jpg',
    title: 'Smiling Australian driver',
    answer: 'Daniel Ricciardo', questionType: 'driver',
    options: ['Daniel Ricciardo', 'Oscar Piastri', 'Mark Webber', 'Max Verstappen'],
    hint: 'Australian | Shoey celebration | Honey badger',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 4,
  },
  {
    id: 'fb-023', type: 'zoomed',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/Carlos_Sainz_Jr._2022_Bahrain_%28cropped%29.jpg/800px-Carlos_Sainz_Jr._2022_Bahrain_%28cropped%29.jpg',
    title: 'Spanish Ferrari driver',
    answer: 'Carlos Sainz', questionType: 'driver',
    options: ['Carlos Sainz', 'Fernando Alonso', 'Pedro Martinez de la Rosa', 'Charles Leclerc'],
    hint: 'Spanish | Son of rally legend | Smooth',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 4,
  },
  {
    id: 'fb-024', type: 'pixelated',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Sergio_P%C3%A9rez_2022_Bahrain_%28cropped%29.jpg/800px-Sergio_P%C3%A9rez_2022_Bahrain_%28cropped%29.jpg',
    title: 'Mexican Red Bull driver',
    answer: 'Sergio Perez', questionType: 'driver',
    options: ['Sergio Perez', 'Carlos Sainz', 'Esteban Ocon', 'Lance Stroll'],
    hint: 'Mexican | Red Bull #11 | Checo',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 4,
  },
  {
    id: 'fb-025', type: 'zoomed',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Alain_Prost_1990_USGP_crop.jpg/800px-Alain_Prost_1990_USGP_crop.jpg',
    title: 'The Professor of F1',
    answer: 'Alain Prost', questionType: 'driver',
    options: ['Alain Prost', 'Ayrton Senna', 'Nigel Mansell', 'Nelson Piquet'],
    hint: 'French | 4x Champion | Senna rival',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 7,
  },
  {
    id: 'fb-026', type: 'pixelated',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Niki_Lauda_1975_Swedish_Grand_Prix.jpg/800px-Niki_Lauda_1975_Swedish_Grand_Prix.jpg',
    title: 'Austrian comeback legend',
    answer: 'Niki Lauda', questionType: 'driver',
    options: ['Niki Lauda', 'James Hunt', 'Jochen Rindt', 'Gerhard Berger'],
    hint: 'Austrian | 3x Champion | Survived Nürburgring 1976',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 7,
  },
  {
    id: 'fb-027', type: 'zoomed',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Circuit_de_Monaco_1.jpg/1280px-Circuit_de_Monaco_1.jpg',
    title: 'Racing through the streets of a principality',
    answer: 'Monaco', questionType: 'circuit',
    options: ['Monaco', 'Singapore', 'Melbourne', 'Baku'],
    hint: 'The jewel of the calendar | Hardest to overtake',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 2,
  },
  {
    id: 'fb-028', type: 'pixelated',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Abu_Dhabi_Grand_Prix_circuit_2021.svg/800px-Abu_Dhabi_Grand_Prix_circuit_2021.svg.png',
    title: 'Season finale desert track',
    answer: 'Abu Dhabi', questionType: 'circuit',
    options: ['Abu Dhabi', 'Bahrain', 'Jeddah', 'Qatar'],
    hint: 'Yas Marina | Season finale | Twilight race',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 4,
  },
  {
    id: 'fb-029', type: 'zoomed',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Oscar_Piastri_2023_Bahrain_%28cropped%29.jpg/800px-Oscar_Piastri_2023_Bahrain_%28cropped%29.jpg',
    title: 'Young Australian McLaren driver',
    answer: 'Oscar Piastri', questionType: 'driver',
    options: ['Oscar Piastri', 'Lando Norris', 'Daniel Ricciardo', 'Mark Webber'],
    hint: 'Australian | McLaren | F2 Champion 2021',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 5,
  },
  {
    id: 'fb-030', type: 'pixelated',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Pierre_Gasly_2021_French_GP_%28cropped%29.jpg/800px-Pierre_Gasly_2021_French_GP_%28cropped%29.jpg',
    title: 'French Alpine driver',
    answer: 'Pierre Gasly', questionType: 'driver',
    options: ['Pierre Gasly', 'Esteban Ocon', 'Romain Grosjean', 'Jules Bianchi'],
    hint: 'French | Won in Monza 2020 | Alpine',
    redditPermalink: 'https://reddit.com/r/formula1', difficulty: 5,
  },
];

export function getFallbackChallengesForLevel(level: number, count: number = 10): F1Challenge[] {
  const shuffled = [...FALLBACK_CHALLENGES].sort(() => Math.random() - 0.5);

  // Assign difficulties based on level proximity
  return shuffled.slice(0, count).map(c => ({
    ...c,
    difficulty: level,
    // Increase pixelation for higher levels
    type: level >= 6
      ? 'pixelated'
      : level >= 3
      ? (Math.random() > 0.5 ? 'pixelated' : 'zoomed')
      : 'zoomed',
  }));
}
